### PR TITLE
Issue 19 get default reactive domain

### PR DESCRIPTION
**Pull request by m-l-1**

### CODE REVIEW

**Comment by m-l-1** [comment]
@DivadNojnarg Could you please try this branch and let me know. It should fix your issue with automatic input ports forwarding from parent to child

**Comment by m-l-1** [comment]
@DivadNojnarg Just added a fix for the input ports not being functional in nested mods
As said, I will redesign a bit how the mapping is done in the framework.

**Comment by DivadNojnarg** [comment]
There is something really wrong with `%:i:%` (see my screenshot)
Screenshot 2020-02-11 at 18 38 54

How do you explain that I start with a parent module with some input ports well defined, a nested module with 0 inputs. I copy all inputs from the parent on the nested module with `%:i:%`. The result seems ok but when I print the nested mod again, it is still without input ports? I guess there is still issue with the session since it is not the same

**Comment by DivadNojnarg** [comment]
What is really weird is that when I do `self$nested_mod[[1]]` in debug, the session is global_session. When I do `self$getSessionId()`, I get "151a96bbe73d89cf77319b20914d5518".

**Comment by m-l-1** [comment]
There must a good reason ;-) will debug the nested mods in list later. It
should definitely be in the current session.

M

**Review by DivadNojnarg — APPROVED** [review]

**Comment by DivadNojnarg** [comment]
Ready to go

**Pull request merged**
