### PR TITLE
Add shiny namespace to tabPanel

### PR DESCRIPTION
**Pull request by stefaneng**
Otherwise collides with bs4Dash if loaded

### CODE REVIEW

**Comment by m-l-1** [comment]
This is done on purpose to allow the UI of Store to work when injected in a {bs4Dash} dashboard. What is your search path and what do you want to use it in shiny/bs4Dash?

**Comment by stefaneng** [comment]
I am getting an error:

> Error in tabPanel("Sessions", fluidRow(br(), DT::dataTableOutput(self$ns("sessions")))) : 
  argument "tabName" is missing, with no default

I want to use it in bs4Dash for subpat.

**Comment by m-l-1** [comment]
Can you share your search path ? search()

**Comment by stefaneng** [comment]
It worked when I moved the tidymodules library load before subpat:

```{r}
library(subpat)
library(tidymodules)
library(bs4Dash)
```

**Comment by m-l-1** [comment]
Are you far for submitting ?

**Pull request closed without merging**
